---
title: "Portfolio Reginald van Putt"
author: "Reginald van Putt"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
date: "2024-02-21"
---
```{r variabels, echo=FALSE}
library(tidyverse)
library(spotifyr)
id <- "3224ef21d8e245689234aa11d3f2e919"
secret <-"f83518a285bd4bdfbfd77bdda440df7e"
Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
access_token <- get_spotify_access_token()
```

```{r loading_playlists, echo=FALSE}
loading_playlists <- function(x) {
pb_features = get_playlist_audio_features("","1dDP0J8kZlyQJ1kw2heuqN") #1
pb_features_2 = get_playlist_audio_features("","5f67hG4cT4vuCbpp2ZJSAC") #2
cs_features = get_playlist_audio_features("","1xAbFlGMk4NeTcHlXVxNIT") #1
bs_features = get_playlist_audio_features("","55RF4Rd8rbn4cYKS5fCn2r") #1
#ce_features = get_playlist_audio_features("","") #1, not done
medicine_features = get_playlist_audio_features("","5BTPZghhEMr9e6mfGHmv0A") #1
id_features = get_playlist_audio_features("","01HKzQnzQ5XLn5OefshdIx") #1
me_features = get_playlist_audio_features("","1kZBSsmIMAUocJgM6Dm32F") #1
psychology_features = get_playlist_audio_features("","7lN3BZW8AhOzpLpyPY5FqA") #1
biology_features = get_playlist_audio_features("","2ZyiCXQK1GUCfp33TSOQO6") #1
sw_features = get_playlist_audio_features("","7FfkG5ZbE9IhpJNOHBqRZM") #1
ai_features = get_playlist_audio_features("","61qvD51DpYY12Sh0GDsmwl") #1
}

```

```{r faculty_dividing, echo=FALSE}
faculty_dividing <- function(x) {
sci = "Faculty of Science"
hum = "Faculty of Humanities"
med = "Faculty of Medicine"
tech = "Technical University studies"
soc = "Social and Behavior studies"

final_data <-
  bind_rows(
    pb_features |> mutate(bachelor = "Psychobiology", faculty = sci),
    pb_features_2 |> mutate(bachelor = "Psychobiology", faculty = sci),
    cs_features |> mutate(bachelor = "Communication science", faculty = soc),
    bs_features |> mutate(bachelor = "Biomedical science", faculty = sci),
    #ce_features |> mutate(bachelor = "Civil engineering"),
    medicine_features |> mutate(bachelor = "Medicine", faculty = med),
    id_features |> mutate(bachelor = "Industrial engineering", faculty = tech),
    me_features |> mutate(bachelor = "Mechanical engineering", faculty = tech),
    psychology_features |> mutate(bachelor = "Psychology", faculty = soc),
    biology_features |> mutate(bachelor = "Biology", faculty = sci),
    sw_features |> mutate(bachelor = "Social works", faculty = soc),
    ai_features |> mutate(bachelor = "Artifical intelligence", faculty = sci)
  )
}
```

```{r make_plot, echo = FALSE}
make_plot <- function(x) {
final_data |>                    # Start with awards.
  mutate(
    mode = ifelse(mode == 0, "Minor", "Major")
  ) |>
  ggplot(                     # Set up the plot.
    aes(
      x = valence,
      y = energy,
      size = loudness,
      colour = bachelor
    )
  ) +
  geom_point() +              # Scatter plot.
  geom_rug(linewidth = 0.1) + # Add 'fringes' to show data distribution.
  geom_text(                  # Add text labels from above.
    aes(
      x = valence,
      y = energy,
      label = label
    ),
    data = 
      tibble(
        label = c("", ""), #top and bottom labels
        category = c("Edisons", "Grammys"),
        valence = c(0.104, 0.0339),
        energy = c(0.992, 0.00166)
      ),
    colour = "black",         # Override colour (not mode here).
    size = 3,                 # Override size (not loudness here).
    hjust = "left",           # Align left side of label with the point.
    vjust = "center",         # Align vertical center of label with the point.
    nudge_x = 0.02            # Nudge the label slightly right.
  ) +
  facet_wrap(~ faculty) +    # Separate charts per playlist.
  scale_x_continuous(         # Fine-tune the x axis.
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),   # Use grid-lines for quadrants only.
    minor_breaks = NULL       # Remove 'minor' grid-lines.
  ) +
  scale_y_continuous(         # Fine-tune the y axis in the same way.
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),
    minor_breaks = NULL
  ) +
  scale_colour_brewer(        # Use the Color Brewer to choose a palette.
    type = "qual",            # Qualitative set.
    palette = "Paired"        # Name of the palette is 'Paired'.
  ) +
  scale_size_continuous(      # Fine-tune the sizes of each point.
    trans = "exp",            # Use an exp transformation to emphasise loud.
    guide = "none"            # Remove the legend for size.
  ) +
  theme_light() +             # Use a simpler theme.
  labs(                       # Make the titles nice.
    x = "Valence",
    y = "Energy",
    title = "Top 5 songs for different bachelors",
    colour = "Bachelor"
  )
}
```

### Introduction
Welcome to my portfolio etc!

### Visualization

This page will show your data/graphs etc.

***
This is a sidebar from the plot.

### Discussion/conclusion

The discussion and conclusion will display here. 
Let's test if something is broken or not





